# Generated by Django 2.0.2 on 2018-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogue',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('issue_status', models.BooleanField(default=False)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
