# Generated by Django 2.0.2 on 2018-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='curr_user',
            field=models.IntegerField(default=None),
        ),
    ]
