# Generated by Django 2.0.2 on 2018-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20181123_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='issueRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=None)),
                ('book', models.IntegerField(default=None)),
                ('user', models.IntegerField(default=None)),
            ],
        ),
    ]
