# Generated by Django 2.0.2 on 2018-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20181123_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='issueregister',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pending_fines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='batch',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
