# Generated by Django 2.0.2 on 2018-11-24 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20181124_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 19, 57, 26, 115360)),
        ),
    ]
