# Generated by Django 2.0.2 on 2018-11-24 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20181124_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 30, 19, 895193)),
        ),
    ]
